---
title: "ESCA Signage Committee Proposed Locations"
output: 
  html_document:
    css: "styles.css"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(leaflet)
library(RColorBrewer)
source("set_up.R")
```

```{r, echo = FALSE, fig.align='center'}
# Palette ======================================================================
owner_pal <- colorFactor(palette = brewer.pal(
  length(unique(esca[["land_holder"]])), "Paired"),
  domain = esca[["land_holder"]],
  na.color = "#FFFFFF")
# Icons ========================================================================
customIcons <- iconList(
  gate = makeIcon("imgs/gate.png", "imgs/gate.png", 12, 12),
  info = makeIcon("imgs/information.png", "imgs/information.png", 12, 12),
  restricted = makeIcon("imgs/no-entry.png", "imgs/no-entry.png", 12, 12),
  parking = makeIcon("imgs/no-parking.png", "imgs/no-parking.png", 12, 12)
)
# Map ==========================================================================
leaflet() |>
  addProviderTiles(provider = providers[['Esri.WorldImagery']],
                   group    = "Imagery") |>
  setView(lng = -121.798, lat = 36.615, #36.613,
            zoom = 12.5) |>
  addMeasure(position          = "topright",
             primaryLengthUnit = "feet", 
             primaryAreaUnit   = "acres") |>
  addPolygons(data = fo, fill = FALSE, weight = 2, color = "#FFFFFF",
              opacity = 1, dashArray = 4, 
              label = "Former Fort Ord Boundary") |>
  addPolygons(data = esca, fill = TRUE, color = "#FFFFFF", popup = ~mra_popup,
              fillColor = ~owner_pal(esca[["land_holder"]]), 
              opacity = 1, weight = 1, fillOpacity = 0.5) |>
  addMarkers(data = signs, icon = ~customIcons[signs[["icon"]]], 
             popup = paste0("<table>",
                            "<tr><th>Name: </th><td>", signs[["name"]], "</td>",
                            "<tr><th>Proposed Type: </th><td>", signs[["cat"]], "</td>",
                            "<tr><th>Proposed Content: </th><td>", signs[["content"]], "</td>",
                            "<tr><th>Property Owner: </th><td>", signs[["jurisdiction"]], "</td>",
                            "<tr><th>Trim Color: </th><td style='background-color: ", signs[["color"]], "'></td>",
                            "</table>"), 
             clusterOptions = markerClusterOptions(showCoverageOnHover = TRUE,
                                                   spiderfyOnMaxZoom = TRUE, maxZoom = 100)
             ) |>
  addLegend(position = "bottomleft", pal = owner_pal,
            values = esca[["land_holder"]], title = "Land Owners")
```

