---
title: "Draft Signs and Locations Table"
output: 
  html_document:
    css: "styles.css"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo    = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r data, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
library(data.table)
library(DT)
invisible(source("set_up.R"))
```

```{r}
setDT(signs)[, c("Name", "Property Owner", "Sign Type", 
                         "Proposed Sign Content", "Latitude",
                         "Longitude") := .(name, jurisdiction, cat, content, 
                                           Latitude, Longitude)
                     ][, c("Name", "Property Owner", "Sign Type", 
                           "Proposed Sign Content", "Latitude", "Longitude")] |>
  DT::datatable(escape = FALSE, rownames = FALSE,
                # caption = htmltools::tags$caption(style = "text-align: center; color: #808080",
                #                                   htmltools::tags$h3("Draft Signs and Locations")),
                options = list(dom = "ftip",
                               search = list(regex           = TRUE, 
                                             caseInsensitive = TRUE)))
```

