---
title: "Draft Signs and Locations Table"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo    = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{css}
html *
  {
    color: #808080
    font-family: Arial !important;
  }
```

```{r data}
library(DT)
library(dplyr)
## Signage ---------------------------------------------------------------------
gateways <- data.frame(
  name = c(
    # COS
    "Coe and GJMB", "Parker Flats Road", "Parker Flats Cut Off Road",
    "Parker Flats Cut Off Road",
    # MOCO
    "Parker Flats Road",
    "8th and Giggling 1", "8th and Giggling 2", "8th and Giggling 3",
    "Jerry Smith and Inter-Garrison", "Inter-Garrison",
    "West Camp and Inter-Garrison", "Barloy Canyon", "Barloy Canyon and Trail 50",
    # CSUMB
    "8th", "Inter-Garrison 1", "Inter-Garrison 2", "Inter-Garrison 3", "Inter-Garrison 4"
           ),
  jurisdiction = c(
    # COS
    "COS", "COS", "COS",
    "COS", 
    # MOCO
    "MOCO",
    "MOCO", "MOCO", "MOCO", 
    "MOCO", "MOCO",
    "MOCO", "MOCO", "MOCO",
    # CSUMB
    "CSUMB", "CSUMB", "CSUMB", "CSUMB", "CSUMB" 
    ),
  lat  = c(
    # COS
    36.621491, 36.637419,  36.636610,
    36.639727, 
    # MOCO
    36.638896, 
    36.643462, 36.643329, 36.643493, 
    36.655309, 36.655412, 
    36.651261, 36.644026, 36.633189, 
    # CSUMB
    36.649455, 36.654560, 36.654594, 36.654857, 36.654890
  ),
  lon  = c(
    # COS
    -121.816935, -121.796371, -121.79834,
    -121.798528, 
    # MOCO
    -121.79172,
    -121.787673, -121.787115, -121.786766,
    -121.757936, -121.748820, 
    -121.747330, -121.730626, -121.735757,
    # CSUMB
    -121.786622, -121.784548, -121.782094, -121.776586, -121.773236),
  cat = "Usage Control Sign", icon = "info")
closed <- data.frame(
  name = c("Monterey MRA", "Monterey MRA", "Monterey MRA", "Monterey MRA",
           "MOUT", "MOUT", "MOUT", "MOUT",
           "Future East Garrison"),
  jurisdiction = c("COM", "COM", "COM", "COM",
                   "MPC", "MPC", "MPC", "MPC",
                   "MOCO"),
  lat  = c(36.589996, 36.588325, 36.588187, 36.58624,
           36.621742, 36.621048, 36.618469, 36.61588,
           36.64057),
  lon  = c(-121.825735, -121.823289, -121.827591, -121.824614,
           -121.748838, -121.749864, -121.75445, -121.756928,
           -121.735231),
  cat = "Restricted Area Sign", icon = "restricted")
gates <- data.frame(
  name = c("Eucalyptus Road - Gate 1", "Paker Flats Cutoff Road - Gate 1",
           "Parker Flats Road - Gate 1", "8th Avenue Extension - Gate 1",
           "Gigling Road - Gate 1", "Gigling Road - Gate 2", 
           "Watkins Gate Road - Gate 1", "Watkins Gate Road - Gate 2",
           "Barloy Canyon Road - Gate 1", "Cresent Bluff Road - Gate 1",
           "Barloy Canyon Road - Gate 2", "Barloy Canyon Road Gate 3",
           "Impossible Canyon South Gate", # Ask Betsy
           "South Boundary Road - Gate 1", "Impossible Canyon North Gate",
           "GJMB Gate 1", "GJMB Gate 2", "GJMB Gate 3", "Blue Line Gate"),
  jurisdiction = c("MOCO", "COS",
                   "COS", "MOCO",
                   "MOCO", "MOCO",
                   "MOCO", "MOCO",
                   "MOCO", "MOCO",
                   "MOCO", "MOCO",
                   "MOCO",
                   "MOCO", "Army",
                   "COS", "COS", "COS", "COS"),
  lat  = c(36.62952, 36.635735, 
           36.63786, 36.643302, 
           36.643541, 36.643437,
           36.65101, 36.65092,
           36.649803, 36.647442,
           36.624422, 36.585594,
           36.586061,
           36.589382, 36.623846,
           36.614670, 36.609714, 36.600471, 36.627099),
  lon  = c(-121.791962, -121.7973, 
           -121.793841, -121.78706,
           -121.786886, -121.784931,
           -121.744676, -121.741460,
           -121.731947, -121.731581,
           -121.742066, -121.761653,
           -121.760641,
           -121.752686, -121.747318,
           -121.819669, -121.822165, -121.826696, -121.798062),
  cat = "Gate Access Signage", icon = "gate")
signs <- rbind(gateways, closed, gates)
```

```{r}
signs %>% 
  mutate(jurisdiction = case_when(jurisdiction == "COM" ~ "City of Monterey",
                                  jurisdiction == "COS" ~ "City of Seaside",
                                  jurisdiction == "MOCO" ~ "County of Monterey",
                                  jurisdiction == "Army" ~ "Army",
                                  jurisdiction == "CSUMB" ~ "CSUMB",
                                  jurisdiction == "MPC" ~ "MPC"),
         `Proposed Sign Content` = case_when(cat == "Gate Access Signage"  ~ "<ul><li>Jurisdiction logo and name</li></br><li>Gate Name</li></br><li>Restrictions (e.g., Authorized Vehicles Only)</li></br><li>Access Information (e.g., For access call (831) 394-6811)</li></ul>",
                                             cat == "Restricted Area Sign" ~ "<ul><li>Jurisdiction logo and name</li></br><li>Restrictions (e.g., NO TRESSPASSING Violators will be prosecuted)</li></br><li>Code (e.g.,PC 602 Enforced)</li></ul>",
                                             cat == "Usage Control Sign"   ~ "<ul><li>Jurisdiction logo, name and contact information</li></br><li>Restrictions (e.g., use restricted to signed trails)</li></br><li>Allowed or prohibited use symbols</li></br><li>Additional information (e.g., QR code and 3Rs)</li></ul>")) %>%
  select(Name = name, `Property Owner` = jurisdiction, `Sign Type` = cat, `Proposed Sign Content`, Latitude = lat, Longitude = lon) %>%
  DT::datatable(escape = FALSE, rownames = FALSE,
                # caption = htmltools::tags$caption(style = "text-align: center; color: #808080",
                #                                   htmltools::tags$h3("Draft Signs and Locations")),
                options = list(dom = "ftip",
                               search = list(regex           = TRUE, 
                                             caseInsensitive = TRUE)))
```

